/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;


import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gianm
 */
public class FormularioGine extends javax.swing.JFrame {

    /**
     * Creates new form FormularioGine
     */
     FondoPanel fondo = new FondoPanel();
    
    public FormularioGine() {
        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
    }

     @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono-embarazo.jpg"));
        return retValue;
    }
    
    private final String dataBase = "tablaregistro2";
    private final String user = "root";
    private final String password = "diego105";
    private final String URL = "jdbc:mysql://localhost:3306/" + dataBase + "?autoReconnect=true&useSSL=false";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel();
        ePatologiaGine = new javax.swing.JLabel();
        campoPatologiaGine = new javax.swing.JTextField();
        etiquetaTratamiento = new javax.swing.JLabel();
        campoTratamiento = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        edad = new javax.swing.JLabel();
        campoRauG = new javax.swing.JTextField();
        campoEdadG = new javax.swing.JTextField();
        rau = new javax.swing.JLabel();
        campoControlMedicoG = new javax.swing.JTextField();
        campoFurG = new javax.swing.JTextField();
        campoGestacionesG = new javax.swing.JTextField();
        gestaciones = new javax.swing.JLabel();
        controlMedico = new javax.swing.JLabel();
        fur = new javax.swing.JLabel();
        campoCirugiasPreG = new javax.swing.JTextField();
        campoPatologiasG = new javax.swing.JTextField();
        campoAlergiasG = new javax.swing.JTextField();
        cirugiasPrevias = new javax.swing.JLabel();
        patologiasBase = new javax.swing.JLabel();
        alergias = new javax.swing.JLabel();
        campoExamenesG = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setLayout(null);

        ePatologiaGine.setText("PATOLOGIA GINECOLOGICA");
        jPanel1.add(ePatologiaGine);
        ePatologiaGine.setBounds(20, 410, 150, 15);
        jPanel1.add(campoPatologiaGine);
        campoPatologiaGine.setBounds(200, 410, 189, 19);

        etiquetaTratamiento.setText("TRATAMIENTO");
        jPanel1.add(etiquetaTratamiento);
        etiquetaTratamiento.setBounds(20, 450, 90, 15);
        jPanel1.add(campoTratamiento);
        campoTratamiento.setBounds(200, 459, 189, 19);

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar);
        botonGuardar.setBounds(12, 512, 74, 25);

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel1.add(volver);
        volver.setBounds(342, 512, 66, 25);

        edad.setText("EDAD");
        jPanel1.add(edad);
        edad.setBounds(20, 70, 80, 15);

        campoRauG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRauGKeyTyped(evt);
            }
        });
        jPanel1.add(campoRauG);
        campoRauG.setBounds(198, 32, 200, 20);

        campoEdadG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoEdadGKeyTyped(evt);
            }
        });
        jPanel1.add(campoEdadG);
        campoEdadG.setBounds(198, 70, 200, 20);

        rau.setText("RAU");
        jPanel1.add(rau);
        rau.setBounds(20, 40, 60, 15);
        jPanel1.add(campoControlMedicoG);
        campoControlMedicoG.setBounds(200, 150, 200, 20);
        jPanel1.add(campoFurG);
        campoFurG.setBounds(200, 189, 200, 20);
        jPanel1.add(campoGestacionesG);
        campoGestacionesG.setBounds(201, 110, 200, 20);

        gestaciones.setText("GESTACIONES");
        jPanel1.add(gestaciones);
        gestaciones.setBounds(20, 110, 140, 15);

        controlMedico.setText("CONTROLES MEDICOS");
        jPanel1.add(controlMedico);
        controlMedico.setBounds(20, 150, 140, 15);

        fur.setText("FUR");
        jPanel1.add(fur);
        fur.setBounds(20, 190, 120, 15);
        jPanel1.add(campoCirugiasPreG);
        campoCirugiasPreG.setBounds(200, 227, 191, 20);
        jPanel1.add(campoPatologiasG);
        campoPatologiasG.setBounds(200, 270, 191, 20);
        jPanel1.add(campoAlergiasG);
        campoAlergiasG.setBounds(200, 308, 191, 20);

        cirugiasPrevias.setText("CIRUGIAS PREVIAS");
        jPanel1.add(cirugiasPrevias);
        cirugiasPrevias.setBounds(20, 230, 130, 15);

        patologiasBase.setText("PATOGIAS BASE");
        jPanel1.add(patologiasBase);
        patologiasBase.setBounds(20, 270, 110, 15);

        alergias.setText("ALERGIAS");
        jPanel1.add(alergias);
        alergias.setBounds(20, 310, 70, 15);
        jPanel1.add(campoExamenesG);
        campoExamenesG.setBounds(200, 360, 191, 20);

        jLabel1.setText("EXAMENES");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 360, 70, 15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        FormularioAnamnesis formulario = new FormularioAnamnesis();
        formulario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void campoRauGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRauGKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_campoRauGKeyTyped

    private void campoEdadGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEdadGKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_campoEdadGKeyTyped

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        if ( "".equals(campoPatologiaGine.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo ACO");
        }
        if ( "".equals(campoTratamiento.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Edad Gestacional"); 
        }
        
        else {
            ResultSet rs = null;
        Connection conexion = getConexion();
            try{
           PreparedStatement ps = conexion.prepareStatement("UPDATE registro set RAU=?, EDAD=?, gestaciones=?, Control=?, FUR=?, Cirugias=?, Patoligias=?, Alergias=?, Examenes=?, ACO=?, gestacion=?, Matrona=?, Ginecologico=?, Tratamiento=? Where RAU ="+campoRauG.getText());
            ps.setString(1, campoRauG.getText());
            ps.setString(2, campoEdadG.getText());
            ps.setString(3, campoGestacionesG.getText());
            ps.setString(4, campoControlMedicoG.getText());
            ps.setString(5, campoFurG.getText());
            ps.setString(6, campoCirugiasPreG.getText());
            ps.setString(7, campoPatologiasG.getText());
            ps.setString(8, campoAlergiasG.getText());
            ps.setString(9, campoExamenesG.getText());
            ps.setString(10, "-");
            ps.setString(11, "-");
            ps.setString(12, "-");
            ps.setString(13, campoPatologiaGine.getText());
            ps.setString(14, campoTratamiento.getText());
            
            
            int result = ps.executeUpdate();
       
            if (result>0){
                JOptionPane.showMessageDialog(null, "Registro modificado");
                
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro No modificado");
            }
            conexion.close();
            
            } catch (SQLException ex){
                
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    public Connection getConexion() {
        Connection cn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = (Connection) DriverManager.getConnection(URL, user, password);

//            JOptionPane.showMessageDialog(null, "conexion exitosa");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);

        }
        return cn;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioGine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioGine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioGine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioGine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioGine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alergias;
    private javax.swing.JButton botonGuardar;
    public static javax.swing.JTextField campoAlergiasG;
    public static javax.swing.JTextField campoCirugiasPreG;
    public static javax.swing.JTextField campoControlMedicoG;
    public static javax.swing.JTextField campoEdadG;
    public static javax.swing.JTextField campoExamenesG;
    public static javax.swing.JTextField campoFurG;
    public static javax.swing.JTextField campoGestacionesG;
    private javax.swing.JTextField campoPatologiaGine;
    public static javax.swing.JTextField campoPatologiasG;
    public static javax.swing.JTextField campoRauG;
    private javax.swing.JTextField campoTratamiento;
    private javax.swing.JLabel cirugiasPrevias;
    private javax.swing.JLabel controlMedico;
    private javax.swing.JLabel ePatologiaGine;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel etiquetaTratamiento;
    private javax.swing.JLabel fur;
    private javax.swing.JLabel gestaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patologiasBase;
    private javax.swing.JLabel rau;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

     class FondoPanel extends JPanel{
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/UTERO.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g);
        }
        
    }
    
}
