/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author gianm
 */
public class FormularioObstetricia extends javax.swing.JFrame {

    /**
     * Creates new form FormularioObstetricia
     */

    FondoPanel fondo = new FondoPanel();
    
    public FormularioObstetricia() {
        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
       
         ResultSet rs = null;
        Connection conexion = getConexion();
         
    }
    
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono-embarazo.jpg"));
        return retValue;
    }
    
     private final String dataBase = "tablaregistro2";
    private final String user = "root";
    private final String password = "diego105";
    private final String URL = "jdbc:mysql://localhost:3306/" + dataBase + "?autoReconnect=true&useSSL=false";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new FondoPanel();
        aco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoAcoO = new javax.swing.JTextField();
        campoEdadGestacionalO = new javax.swing.JTextField();
        campoMatronaO = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        campoRauO = new javax.swing.JTextField();
        rau = new javax.swing.JLabel();
        campoPatologiasO = new javax.swing.JTextField();
        cirugiasPrevias = new javax.swing.JLabel();
        campoAlergiasO = new javax.swing.JTextField();
        patologiasBase = new javax.swing.JLabel();
        campoExamenesO = new javax.swing.JTextField();
        alergias = new javax.swing.JLabel();
        examenes = new javax.swing.JLabel();
        campoEdadO = new javax.swing.JTextField();
        campoGestacionesO = new javax.swing.JTextField();
        edad = new javax.swing.JLabel();
        campoControlMedicoO = new javax.swing.JTextField();
        gestaciones = new javax.swing.JLabel();
        campoFurO = new javax.swing.JTextField();
        controlMedico = new javax.swing.JLabel();
        campoCirugiasPreO = new javax.swing.JTextField();
        etiquetaFur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        aco.setText("ACO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 39, 0, 0);
        jPanel1.add(aco, gridBagConstraints);

        jLabel2.setText("EDAD GESTACIONAL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 39, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("CONTROL MATRONA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 39, 0, 0);
        jPanel1.add(jLabel3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 49, 0, 28);
        jPanel1.add(campoAcoO, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 28);
        jPanel1.add(campoEdadGestacionalO, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 49, 0, 28);
        jPanel1.add(campoMatronaO, gridBagConstraints);

        botonGuardar.setText("GUARDAR");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 42, 24, 0);
        jPanel1.add(botonGuardar, gridBagConstraints);

        botonVolver.setText("VOLVER");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 151, 24, 0);
        jPanel1.add(botonVolver, gridBagConstraints);

        campoRauO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRauOKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 49, 0, 28);
        jPanel1.add(campoRauO, gridBagConstraints);

        rau.setText("RAU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 39, 0, 0);
        jPanel1.add(rau, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 28);
        jPanel1.add(campoPatologiasO, gridBagConstraints);

        cirugiasPrevias.setText("CIRUGIAS PREVIAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 39, 0, 0);
        jPanel1.add(cirugiasPrevias, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 49, 0, 28);
        jPanel1.add(campoAlergiasO, gridBagConstraints);

        patologiasBase.setText("PATOGIAS BASE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 39, 0, 0);
        jPanel1.add(patologiasBase, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 28);
        jPanel1.add(campoExamenesO, gridBagConstraints);

        alergias.setText("ALERGIAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 39, 0, 0);
        jPanel1.add(alergias, gridBagConstraints);

        examenes.setText("EXAMENES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 45, 0, 0);
        jPanel1.add(examenes, gridBagConstraints);

        campoEdadO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoEdadOKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 28);
        jPanel1.add(campoEdadO, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 49, 0, 28);
        jPanel1.add(campoGestacionesO, gridBagConstraints);

        edad.setText("EDAD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 39, 0, 0);
        jPanel1.add(edad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 28);
        jPanel1.add(campoControlMedicoO, gridBagConstraints);

        gestaciones.setText("GESTACIONES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 39, 0, 0);
        jPanel1.add(gestaciones, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 49, 0, 28);
        jPanel1.add(campoFurO, gridBagConstraints);

        controlMedico.setText("CONTROLES MEDICOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 39, 0, 0);
        jPanel1.add(controlMedico, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 49, 0, 28);
        jPanel1.add(campoCirugiasPreO, gridBagConstraints);

        etiquetaFur.setText("FUR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 39, 0, 0);
        jPanel1.add(etiquetaFur, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        FormularioAnamnesis formulario = new FormularioAnamnesis();
        formulario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
 
        
        if ( "".equals(campoAcoO.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo ACO");
        }
        if ( "".equals(campoEdadGestacionalO.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Edad Gestacional"); 
        }
        if ( "".equals(campoMatronaO.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Control Matrona");
        }
        else {
            ResultSet rs = null;
        Connection conexion = getConexion();
            try{
           PreparedStatement ps = conexion.prepareStatement("UPDATE registro set RAU=?, EDAD=?, gestaciones=?, Control=?, FUR=?, Cirugias=?, Patoligias=?, Alergias=?, Examenes=?, ACO=?, gestacion=?, Matrona=?, Ginecologico=?, Tratamiento=? Where RAU ="+campoRauO.getText());
            ps.setString(1, campoRauO.getText());
            ps.setString(2, campoEdadO.getText());
            ps.setString(3, campoGestacionesO.getText());
            ps.setString(4, campoControlMedicoO.getText());
            ps.setString(5, campoFurO.getText());
            ps.setString(6, campoCirugiasPreO.getText());
            ps.setString(7, campoPatologiasO.getText());
            ps.setString(8, campoAlergiasO.getText());
            ps.setString(9, campoExamenesO.getText());
            ps.setString(10, campoAcoO.getText());
            ps.setString(11, campoEdadGestacionalO.getText());
            ps.setString(12, campoMatronaO.getText());
            ps.setString(13, "-");
            ps.setString(14, "-");
            
            
            int result = ps.executeUpdate();
       
            if (result>0){
                JOptionPane.showMessageDialog(null, "Registro modificado");
                
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro No modificado");
            }
            conexion.close();
            
            } catch (SQLException ex){
                
            }
        }
            
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void campoRauOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRauOKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_campoRauOKeyTyped

    private void campoEdadOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEdadOKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_campoEdadOKeyTyped

    public Connection getConexion() {
        Connection cn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = (Connection) DriverManager.getConnection(URL, user, password);

//            JOptionPane.showMessageDialog(null, "conexion exitosa");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);

        }
        return cn;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioObstetricia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioObstetricia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioObstetricia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioObstetricia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioObstetricia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aco;
    private javax.swing.JLabel alergias;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoAcoO;
    public static javax.swing.JTextField campoAlergiasO;
    public static javax.swing.JTextField campoCirugiasPreO;
    public static javax.swing.JTextField campoControlMedicoO;
    private javax.swing.JTextField campoEdadGestacionalO;
    public static javax.swing.JTextField campoEdadO;
    public static javax.swing.JTextField campoExamenesO;
    public static javax.swing.JTextField campoFurO;
    public static javax.swing.JTextField campoGestacionesO;
    private javax.swing.JTextField campoMatronaO;
    public static javax.swing.JTextField campoPatologiasO;
    public static javax.swing.JTextField campoRauO;
    private javax.swing.JLabel cirugiasPrevias;
    private javax.swing.JLabel controlMedico;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel etiquetaFur;
    private javax.swing.JLabel examenes;
    private javax.swing.JLabel gestaciones;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patologiasBase;
    private javax.swing.JLabel rau;
    // End of variables declaration//GEN-END:variables

    
    class FondoPanel extends JPanel{
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/madreCorazon.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g);
        }
        
    }
    
}
