/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFinal;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author gianm
 */
public class FormularioAnamnesis extends javax.swing.JFrame {

    /**
     * Creates new form FormularioAnamnesis
     */
    FondoPanel fondo = new FondoPanel();
    
    public FormularioAnamnesis() {
         this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null);
    }
    
     @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono-embarazo.jpg"));
        return retValue;
    }
    
    private final String dataBase = "tablaregistro2";
    private final String user = "root";
    private final String password = "diego105";
    private final String URL = "jdbc:mysql://localhost:3306/" + dataBase + "?autoReconnect=true&useSSL=false";
    
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new FondoPanel();
        rau = new javax.swing.JLabel();
        edad = new javax.swing.JLabel();
        gestaciones = new javax.swing.JLabel();
        controlMedico = new javax.swing.JLabel();
        fur = new javax.swing.JLabel();
        cirugiasPrevias = new javax.swing.JLabel();
        patologiasBase = new javax.swing.JLabel();
        alergias = new javax.swing.JLabel();
        examenes = new javax.swing.JLabel();
        campoRau = new javax.swing.JTextField();
        campoEdad = new javax.swing.JTextField();
        campoGestaciones = new javax.swing.JTextField();
        campoControlMedico = new javax.swing.JTextField();
        campoFur = new javax.swing.JTextField();
        campoCirugiasPre = new javax.swing.JTextField();
        campoPatologias = new javax.swing.JTextField();
        campoAlergias = new javax.swing.JTextField();
        campoExamenes = new javax.swing.JTextField();
        rBotonObstetrica = new javax.swing.JRadioButton();
        rBotonGinecologica = new javax.swing.JRadioButton();
        rBotonOtro = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        rau.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        rau.setForeground(new java.awt.Color(0, 0, 0));
        rau.setText("RAU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        jPanel1.add(rau, gridBagConstraints);

        edad.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        edad.setForeground(new java.awt.Color(0, 0, 0));
        edad.setText("EDAD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 0);
        jPanel1.add(edad, gridBagConstraints);

        gestaciones.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        gestaciones.setForeground(new java.awt.Color(0, 0, 0));
        gestaciones.setText("GESTACIONES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 6, 0, 0);
        jPanel1.add(gestaciones, gridBagConstraints);

        controlMedico.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        controlMedico.setForeground(new java.awt.Color(0, 0, 0));
        controlMedico.setText("CONTROLES MEDICOS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 6, 0, 0);
        jPanel1.add(controlMedico, gridBagConstraints);

        fur.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        fur.setForeground(new java.awt.Color(0, 0, 0));
        fur.setText("FUR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 0);
        jPanel1.add(fur, gridBagConstraints);

        cirugiasPrevias.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        cirugiasPrevias.setForeground(new java.awt.Color(0, 0, 0));
        cirugiasPrevias.setText("CIRUGIAS PREVIAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 0);
        jPanel1.add(cirugiasPrevias, gridBagConstraints);

        patologiasBase.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        patologiasBase.setForeground(new java.awt.Color(0, 0, 0));
        patologiasBase.setText("PATOGIAS BASE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipady = -5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(25, 6, 0, 0);
        jPanel1.add(patologiasBase, gridBagConstraints);

        alergias.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        alergias.setForeground(new java.awt.Color(0, 0, 0));
        alergias.setText("ALERGIAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 0);
        jPanel1.add(alergias, gridBagConstraints);

        examenes.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        examenes.setForeground(new java.awt.Color(0, 0, 0));
        examenes.setText("EXAMENES");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 0);
        jPanel1.add(examenes, gridBagConstraints);

        campoRau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRauKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 105, 0, 52);
        jPanel1.add(campoRau, gridBagConstraints);

        campoEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoEdadKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 105, 0, 52);
        jPanel1.add(campoEdad, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 105, 0, 52);
        jPanel1.add(campoGestaciones, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 105, 0, 52);
        jPanel1.add(campoControlMedico, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 105, 0, 52);
        jPanel1.add(campoFur, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 105, 0, 52);
        jPanel1.add(campoCirugiasPre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 105, 0, 52);
        jPanel1.add(campoPatologias, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 105, 0, 52);
        jPanel1.add(campoAlergias, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 187;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 105, 0, 52);
        jPanel1.add(campoExamenes, gridBagConstraints);

        buttonGroup1.add(rBotonObstetrica);
        rBotonObstetrica.setText("Paciente Obstetrica");
        rBotonObstetrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBotonObstetricaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        jPanel1.add(rBotonObstetrica, gridBagConstraints);

        buttonGroup1.add(rBotonGinecologica);
        rBotonGinecologica.setText("Paciente Ginecologica");
        rBotonGinecologica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBotonGinecologicaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        jPanel1.add(rBotonGinecologica, gridBagConstraints);

        buttonGroup1.add(rBotonOtro);
        rBotonOtro.setText("No corresponde");
        rBotonOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBotonOtroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 19;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 24, 0, 52);
        jPanel1.add(rBotonOtro, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Indique destino de paciente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 6, 0);
        jPanel1.add(botonGuardar, gridBagConstraints);

        botonMostrar.setText("Mostrar Registro");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 34, 6, 0);
        jPanel1.add(botonMostrar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoRauKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRauKeyTyped
        char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_campoRauKeyTyped

    private void campoEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEdadKeyTyped
      char c = evt.getKeyChar();
        
        if (c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_campoEdadKeyTyped

    private void rBotonObstetricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBotonObstetricaActionPerformed
       FormularioObstetricia formularioObtetricia = new FormularioObstetricia();    
       formularioObtetricia.setVisible(true);
       this.dispose();
       //guardar();
       
       
        FormularioObstetricia.campoRauO.setText(campoRau.getText());
        FormularioObstetricia.campoEdadO.setText(campoEdad.getText());
        FormularioObstetricia.campoGestacionesO.setText(campoGestaciones.getText());
        FormularioObstetricia.campoControlMedicoO.setText(campoControlMedico.getText());
        FormularioObstetricia.campoAlergiasO.setText(campoAlergias.getText());
        FormularioObstetricia.campoPatologiasO.setText(campoPatologias.getText());
        FormularioObstetricia.campoExamenesO.setText(campoExamenes.getText());
        FormularioObstetricia.campoFurO.setText(campoFur.getText());
        FormularioObstetricia.campoCirugiasPreO.setText(campoCirugiasPre.getText());
        

    }//GEN-LAST:event_rBotonObstetricaActionPerformed

    private void rBotonGinecologicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBotonGinecologicaActionPerformed
        FormularioGine formularioGine = new FormularioGine();
        formularioGine.setVisible(true);
        this.dispose();
        //guardar();
        
        FormularioGine.campoRauG.setText(campoRau.getText());
        FormularioGine.campoEdadG.setText(campoEdad.getText());
        FormularioGine.campoGestacionesG.setText(campoGestaciones.getText());
        FormularioGine.campoControlMedicoG.setText(campoControlMedico.getText());
        FormularioGine.campoAlergiasG.setText(campoAlergias.getText());
        FormularioGine.campoPatologiasG.setText(campoPatologias.getText());
        FormularioGine.campoExamenesG.setText(campoExamenes.getText());
        FormularioGine.campoFurG.setText(campoFur.getText());
        FormularioGine.campoCirugiasPreG.setText(campoCirugiasPre.getText());
    
       
    }//GEN-LAST:event_rBotonGinecologicaActionPerformed

    private void rBotonOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBotonOtroActionPerformed
        JOptionPane.showMessageDialog(null, "Usuaria no corresponde antencion Gineco-Obstetra");
    }//GEN-LAST:event_rBotonOtroActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
       guardar();
    }//GEN-LAST:event_botonGuardarActionPerformed

    public void guardar(){
          if ( "".equals(campoRau.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Rau");
        }
         if ( "".equals(campoEdad.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Edad");
        }   
         if ( "".equals(campoGestaciones.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Gestaciones");
        }  
         if ( "".equals(campoControlMedico.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Control Medico");
        }  
         if ( "".equals(campoFur.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Fur");
        }   
         if ( "".equals(campoCirugiasPre.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Cirugias Previas");
        }   
         if ( "".equals(campoPatologias.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Patologias Base");
        }
         if ( "".equals(campoAlergias.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Alergias");
        } 
         if ( "".equals(campoExamenes.getText())){
            JOptionPane.showMessageDialog(null,"complete el campo Examenes");
        } 
         else{
            
             Connection conexion;
         PreparedStatement ps;

        try {

            conexion = getConexion();
            ps = (PreparedStatement) conexion.prepareStatement("INSERT INTO registro VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, campoRau.getText());
            ps.setString(2, campoEdad.getText());
            ps.setString(3, campoGestaciones.getText());
            ps.setString(4, campoControlMedico.getText());
            ps.setString(5, campoFur.getText()); 
            ps.setString(6, campoCirugiasPre.getText());
            ps.setString(7, campoPatologias.getText());
            ps.setString(8, campoAlergias.getText());
            ps.setString(9, campoExamenes.getText());
            ps.setString(10,"-");
            ps.setString(11,"-"); 
            ps.setString(12,"-");
            ps.setString(13,"-");
            ps.setString(14,"-");
            

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Registro insertado correctamente");
              

            } else {
                JOptionPane.showMessageDialog(null, "Registro no insertado");
            }

            conexion.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex);
    }                                        
         } 
    }
    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        TablaDeRegistros tabla = new TablaDeRegistros();
        tabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMostrarActionPerformed

    public Connection getConexion() {
        Connection cn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = (Connection) DriverManager.getConnection(URL, user, password);

//            JOptionPane.showMessageDialog(null, "conexion exitosa");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);

        }
        return cn;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAnamnesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAnamnesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAnamnesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAnamnesis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAnamnesis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alergias;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField campoAlergias;
    public static javax.swing.JTextField campoCirugiasPre;
    public static javax.swing.JTextField campoControlMedico;
    public static javax.swing.JTextField campoEdad;
    public static javax.swing.JTextField campoExamenes;
    public static javax.swing.JTextField campoFur;
    public static javax.swing.JTextField campoGestaciones;
    public static javax.swing.JTextField campoPatologias;
    public static javax.swing.JTextField campoRau;
    private javax.swing.JLabel cirugiasPrevias;
    private javax.swing.JLabel controlMedico;
    private javax.swing.JLabel edad;
    private javax.swing.JLabel examenes;
    private javax.swing.JLabel fur;
    private javax.swing.JLabel gestaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel patologiasBase;
    private javax.swing.JRadioButton rBotonGinecologica;
    private javax.swing.JRadioButton rBotonObstetrica;
    private javax.swing.JRadioButton rBotonOtro;
    private javax.swing.JLabel rau;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/maternidad-bebe.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g);
        }
        
    }
    
}
