package ProyectoFinal;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author gianm
 */
public class TablaDeRegistros extends javax.swing.JFrame {

    /**
     * Creates new form TablaDeRegistros
     */
    
    FondoPanel fondo = new FondoPanel();
    
    public TablaDeRegistros() {
        this.setContentPane(fondo);
        initComponents();
        mostrar();
    }
    
     @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono-embarazo.jpg"));
        return retValue;
    }
    
    private final String dataBase = "TABLAREGISTRO2";
    private final String user = "root";
    private final String password = "diego105";
    private final String URL = "jdbc:mysql://localhost:3306/" + dataBase + "?autoReconnect=true&useSSL=false";

    private Connection cn = null;

    public Connection getConexion() {
        Connection cn = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = (Connection) DriverManager.getConnection(URL, user, password);

            JOptionPane.showMessageDialog(null, "conexion exitosa");
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, "Error " + ex);

        }
        return cn;
    }

    public ResultSet getTabla(String Consulta) {
        Connection cn = getConexion();
        Statement st;
        ResultSet datos = null;

        try {

            st = cn.createStatement();
            datos = st.executeQuery(Consulta);

        } catch (Exception e) {
            System.out.print(e.toString());
        }

        return datos;
    }

    public void mostrar() {
        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaRegistro.setModel(modeloTabla);

        modeloTabla.addColumn("RAU");
        modeloTabla.addColumn("EDAD");
        modeloTabla.addColumn("Gestaciones");
        modeloTabla.addColumn("Controles");
        modeloTabla.addColumn("FUR");
        modeloTabla.addColumn("Cirugias");
        modeloTabla.addColumn("Patologias");
        modeloTabla.addColumn("Alergias");
        modeloTabla.addColumn("Examenes");
        modeloTabla.addColumn("ACO");
        modeloTabla.addColumn("gestaion");
        modeloTabla.addColumn("Matrona");
        modeloTabla.addColumn("Ginecologico");
        modeloTabla.addColumn("Tratamiento");
        PreparedStatement ps;
        ResultSet rs;

        try {
            Connection cn = getConexion();

            ps = (PreparedStatement) cn.prepareStatement("SELECT* FROM Registro");
            rs = ps.executeQuery();

            while (rs.next()) {

                Object fila[] = new Object[14];
                for (int i = 0; i < 14; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException e) {
            System.err.println("Error " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new FondoPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistro = new javax.swing.JTable();
        volver = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        tablaRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "RAU", "EDAD", "GESTACIONES", "C. MEDICOS", "FUR", "CIRUGIAS", "PATOLOGIAS", "ALERGIAS", "EXAMENES", "ACO", "E.GESTACIONAL", "C. MATRONA", "P. GINECOLOGICA", "TRATAMIENTO"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistro);
        if (tablaRegistro.getColumnModel().getColumnCount() > 0) {
            tablaRegistro.getColumnModel().getColumn(0).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1818;
        gridBagConstraints.ipady = 264;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 22, 502, 55);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 15, 0, 0);
        jPanel1.add(volver, gridBagConstraints);

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        jPanel1.add(eliminar, gridBagConstraints);

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 15, 0, 0);
        jPanel1.add(buscar, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        FormularioAnamnesis formulario = new FormularioAnamnesis();
        formulario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Connection conexion;
        PreparedStatement ps;

        try {

            conexion = getConexion();
            ps = (PreparedStatement) conexion.prepareStatement("DELETE FROM Registro WHERE RAU=?");
            ps.setString(1, JOptionPane.showInputDialog("Ingrese el numero de RAU a eliminar"));

            int result = ps.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(null, "Registro eliminado de manera exitosa");
                mostrar();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado");
            }

            conexion.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex);
        }

    }//GEN-LAST:event_eliminarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        Connection conexion;
        PreparedStatement ps;
        ResultSet rs;

        DefaultTableModel modeloTabla = new DefaultTableModel();
        tablaRegistro.setModel(modeloTabla);

        modeloTabla.addColumn("RAU");
        modeloTabla.addColumn("EDAD");
        modeloTabla.addColumn("Gestaciones");
        modeloTabla.addColumn("Controles");
        modeloTabla.addColumn("FUR");
        modeloTabla.addColumn("Cirugias");
        modeloTabla.addColumn("Patologias");
        modeloTabla.addColumn("Alergias");
        modeloTabla.addColumn("Examenes");
        modeloTabla.addColumn("ACO");
        modeloTabla.addColumn("gestaion");
        modeloTabla.addColumn("Matrona");
        modeloTabla.addColumn("Ginecologico");
        modeloTabla.addColumn("Tratamiento");

        try {

            conexion = getConexion();
            ps = (PreparedStatement) conexion.prepareStatement("SELECT* FROM Registro WHERE RAU=?");
            ps.setString(1, JOptionPane.showInputDialog("Ingrese el numero de RAU a buscar"));
            rs = ps.executeQuery();

            while (rs.next()) {

                Object fila[] = new Object[14];
                for (int i = 0; i < 14; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modeloTabla.addRow(fila);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaDeRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaDeRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaDeRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaDeRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaDeRegistros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton eliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaRegistro;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

     
    class FondoPanel extends JPanel{
        
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/imagenes/maternidad-bebe.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            
            setOpaque(false);
            super.paint(g);
        }
        
    }
}
